### ISSUE TITLE
[Bug]: k8s_crd_projectcalico_org_felix_configuration_v1 is successfully executing but not making changes to AWS cluster

### ISSUE THREAD

**Issue by elroydsouza** [metio/terraform-provider-k8s#114]
### Relevant Terraform configuration

// We have an existing calico felix configuration called "default" and want to apply the following:

```terraform
resource "k8s_crd_projectcalico_org_felix_configuration_v1" "default-felix-configuration" {
  metadata = {
    name = "default"
  }
  spec = {
    wireguard_enabled = false
  }
}
```

### Relevant log output

// After performing a "terraform plan" I receive a healthy looking "+ create" with the expected information.

```shell
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # k8s_crd_projectcalico_org_felix_configuration_v1.default-felix-configuration will be created
  + resource "k8s_crd_projectcalico_org_felix_configuration_v1" "default-felix-configuration" {
      + api_version = (known after apply)
      + id          = (known after apply)
      + kind        = (known after apply)
      + metadata    = {
          + name = "default"
        }
      + spec        = {
          + wireguard_enabled = false
        }
      + yaml        = (known after apply)
```

// After performing a "terraform apply" it also appears healthy stating it has applied successfully.

// Running a "kubectl get felixconfigurations.crd.projectcalico.org default -o yaml" I do not see the expected "wireguardEnabled = false" value. However, when I run this in manually via "kubectl patch felixconfiguration default --type='merge' -p '{"spec":{"wireguardEnabled":false}}'" I can see the change made.

**Comment by elroydsouza** [comment]
Sorry if I have butchered the format you wanted for submitting an issue! There really isn't any relevant log output here 😄

**Comment by elroydsouza** [comment]
Sorry! I have just found the bit of text that says: 

> This provider only deals with creating Kubernetes manifests. In order to apply those manifests to a running cluster use other providers like the [kubectl provider](https://registry.terraform.io/providers/gavinbunney/kubectl/).

I assume this means the resources from this provider are not actually able to change the cluster itself! May you please confirm this?

**Comment by sebhoss** [comment]
:sweat_smile: yeah that's true - my original idea was to re-use existing providers like kubectl or the official kubernetes one to deal with the apply/diff logic and let this provider just produce YAML manifests that get fed into them. This was supposed to allow me to write HCL instead of YAML and get nice validation for all my manifests out of the box thanks to terraform. Sadly this did not really work out as well as I hoped, since terraform bugs out when feeding an unknown value (the `yaml` field from this provider) into the various existing kubernetes providers.

So I started to write the necessary logic for this provider to apply/diff all resources against an actual cluster itself in the `development` branch but have not finished that yet for various other reasons :sweat:

**Comment by elroydsouza** [comment]
Ah gotcha! Thanks for clarifying that for me 😄 Good luck in completing that!
